blueprint:
  name: ☕ Coffee v1.2 (Schedule-based or Wattage Detection)
  description: "Advanced coffee machine automation with multiple triggering options: schedule-based, wattage-based heat-up detection, user-defined timing, and manual trigger. Features include notifications, auto-shutoff, and manual shutoff detection. 📅☕⚡"
  domain: automation
  input:
    coffee_switch:
      name: Coffee Machine Switch
      description: "The switch entity that controls your coffee machine. This will be used to turn the machine on and off. 🔌"
      selector:
        entity:
          domain:
          - switch
          multiple: false
    person_home:
      name: Person Home
      description: "Select a person entity to check if someone is home before triggering the coffee machine. The automation will only run if this person is 'home'. 🏡"
      selector:
        entity:
          domain:
          - person
          multiple: false
    notification_device:
      name: Notification Device
      description: "Select the mobile device to receive notifications about the coffee machine status. This should be a device with the Home Assistant companion app installed. 📱"
      selector:
        device:
          integration: mobile_app
          multiple: false
    schedule_entity:
      name: Coffee Schedule
      description: "Select a schedule helper entity that determines when the coffee machine should be triggered. The automation will start when this schedule turns 'on'. 📅"
      selector:
        entity:
          domain:
          - schedule
          multiple: false
    manual_trigger:
      name: Enable Manual Trigger
      description: "If enabled, the automation can also be triggered when the coffee machine switch is manually turned on. This allows for on-demand use in addition to scheduled use. 🔄"
      default: false
      selector:
        boolean: {}
    manual_shutoff_detection:
      name: Enable Manual Shutoff Detection
      description: "If enabled, the automation will stop when the coffee machine is manually turned off. ⏹️"
      default: false
      selector:
        boolean: {}
    warmup_mode:
      name: Warmup Mode
      description: Choose between time-based (fixed duration) or wattage-based (monitors power consumption) warmup detection. Wattage-based is more accurate but requires a power monitoring smart plug. ⏱️⚡
      default: time
      selector:
        select:
          options:
          - label: Time-based
            value: time
          - label: Wattage-based
            value: wattage
    warmup_delay:
      name: Warmup Delay
      description: 'For time-based mode: Set the duration to wait for the coffee machine to warm up. This should be long enough for your machine to be ready to brew. ⏱️'
      default: 00:15:00
      selector:
        time: {}
    wattage_sensor:
      name: Wattage Sensor
      description: 'For wattage-based mode: Select the power sensor entity that monitors your coffee machine''s electricity consumption. This should be a sensor from a smart plug or energy monitor. ⚡'
      selector:
        entity:
          domain:
          - sensor
          device_class:
          - power
          multiple: false
    wattage_threshold:
      name: Wattage Threshold
      description: "For wattage-based mode: Set the power consumption level (in watts) below which the coffee machine is considered warmed up and ready. This is typically when the heating element turns off. 🔋"
      default: 10
      selector:
        number:
          min: 0.0
          max: 1000.0
          unit_of_measurement: W
          step: 1.0
    wattage_duration:
      name: Wattage Duration
      description: 'For wattage-based mode: Set how long (in minutes) to continue monitoring after the machine is detected as warmed up. This ensures the machine stays ready. ⏳'
      default: 5
      selector:
        number:
          min: 1.0
          max: 30.0
          unit_of_measurement: minutes
          step: 1.0
    first_message:
      name: First Notification Message
      description: "Customize the message sent when the coffee machine is warmed up and ready to use. 📩"
      default: Your coffee machine is warmed up and ready to brew! ☕
      selector:
        text:
          multiline: false
    second_delay:
      name: Second Delay
      description: Set the time to wait after the first notification before sending a reminder that the machine will turn off soon. ⏱️
      default: 00:15:00
      selector:
        time: {}
    second_message:
      name: Second Notification Message
      description: "Customize the reminder message sent before the coffee machine turns off. 📩"
      default: "Your coffee machine will turn off soon! Last chance for coffee! ☕📴"
      selector:
        text:
          multiline: false
    final_delay:
      name: Final Delay
      description: Set the time to wait after the second notification before automatically turning off the coffee machine. This is the last chance to grab coffee before shutdown. ⏱️
      default: 00:05:00
      selector:
        time: {}
variables:
  coffee_switch: !input coffee_switch
  notification_device: !input notification_device
  person_home: !input person_home
  schedule_entity: !input schedule_entity
  manual_trigger: !input manual_trigger
  manual_shutoff_detection: !input manual_shutoff_detection
  first_message: !input first_message
  second_message: !input second_message
  second_delay: !input second_delay
  final_delay: !input final_delay
trigger:
- platform: state
  entity_id: !input schedule_entity
  to: 'on'
- platform: state
  entity_id: !input coffee_switch
  to: 'on'
  enabled: !input manual_trigger
condition:
- condition: state
  entity_id: !input person_home
  state: home
action:
- device_id: !input notification_device
  domain: mobile_app
  type: notify
  message: !input first_message
- delay: !input second_delay
- device_id: !input notification_device
  domain: mobile_app
  type: notify
  message: !input second_message
  data:
    actions:
      - action: CANCEL_SHUTDOWN
        title: "Don't turn off the coffee machine"
- delay: !input final_delay
- choose:
  - conditions:
      - condition: template
        value_template: '{{ wait.trigger.event.data.action == ''CANCEL_SHUTDOWN'' if wait.trigger else false }}'
    sequence:
      - stop: "User canceled the coffee machine shutdown"
  default:
    - service: switch.turn_off
      target:
        entity_id: !input coffee_switch
mode: restart
